default: &default
  adapter: mysql2
  timeout: 5000
  encoding: utf8
  pool: 5

development: &dev
  <<: *default
  host: localhost
  database: todowebapp_development
  username: devuser # app_user
  password: devpswd # app_user_pswd

test:
  <<: *dev
  host: localhost
  database: todowebapp_test

production:
  <<: *default
  host: localhost
  database: todowebapp_production
  socket: /var/run/mysqld/mysqld.sock
  username: app_user
  password: app_user_pswd
